on: [push, pull_request]
name: test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x, 1.19.x]
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v3
      with:
         path: './src/github.com/inconshreveable/log15'
    # staticcheck needs this for GOPATH
    - run: |
        echo "GOPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        echo "GO111MODULE=off" >> $GITHUB_ENV
        echo "PATH=$GITHUB_WORKSPACE/bin:$PATH" >> $GITHUB_ENV
    - name: Run tests
      run: |
        go get -t -d ./...
        go vet ./...
        go test -race ./...
      working-directory: './src/github.com/inconshreveable/log15'
